language: objective-c
env: GITHUB_RELEASE_VERSION=0.7
before_install: |
  brew unlink `brew list`; \
  brew install coreutils gnu-tar wget; \
  brew link --force coreutils gnu-tar wget; \
  true # ignore failure
script: "./misc/mac.sh"
deploy:
  provider: releases
  api_key:
    secure: ZEhm7mrWAkpQ01og1p31MNMFze4wCsZlY1L6YoNtyr6yCYZ9xwgBAazOXUSDTXf40vsDZOLtTLaibRMworz2GcYSXV1AIyOOtdkQcvBewMI9kLhl9ICu+a+kLv9uc/FbYuYIn7cEYYjpB0YQft3+/sZT9ILhdOOMHsPpAsBkKPQ=
  file: growthforecast-darwin-2level.tar.gz
  skip_cleanup: true
  on:
    repo: shoichikaji/relocatable-perl-growthforecast
    all_branches: true
    tags: true
